// provincesData.js
const provincesData = [
    { id: 11, name: 'Cao Bằng' },
    { id: 12, name: 'Lạng Sơn' },
    { id: 14, name: 'Quảng Ninh' },
    { id: 15, name: 'Hải Phòng' },
    { id: 17, name: 'Thái Bình' },
    { id: 18, name: 'Nam Định' },
    { id: 19, name: 'Phú Thọ' },
    { id: 20, name: 'Thái Nguyên' },
    { id: 21, name: 'Yên Bái' },
    { id: 22, name: 'Tuyên Quang' },
    { id: 23, name: 'Hà Giang' },
    { id: 24, name: 'Lào Cai' },
    { id: 25, name: 'Lai Châu' },
    { id: 26, name: 'Sơn La' },
    { id: 27, name: 'Điện Biên' },
    { id: 28, name: 'Hòa Bình' },
    { id: 40, name: 'Hà Nội' },
    { id: 34, name: 'Hải Dương' },
    { id: 35, name: 'Ninh Bình' },
    { id: 36, name: 'Thanh Hóa' },
    { id: 37, name: 'Nghệ An' },
    { id: 38, name: 'Hà Tĩnh' },
    { id: 39, name: 'Đồng Nai' },
    { id: 43, name: 'Đà Nẵng' },
    { id: 47, name: 'Đắk Lắk' },
    { id: 48, name: 'Đắk Nông' },
    { id: 49, name: 'Lâm Đồng' },
    { id: 59, name: 'TP. Hồ Chí Minh' },
    { id: 61, name: 'Bình Dương' },
    { id: 62, name: 'Long An' },
    { id: 63, name: 'Tiền Giang' },
    { id: 64, name: 'Vĩnh Long' },
    { id: 65, name: 'Cần Thơ' },
    { id: 66, name: 'Đồng Tháp' },
    { id: 67, name: 'An Giang' },
    { id: 68, name: 'Kiên Giang' },
    { id: 69, name: 'Cà Mau' },
    { id: 70, name: 'Tây Ninh' },
    { id: 71, name: 'Bến Tre' },
    { id: 72, name: 'Bà Rịa – Vũng Tàu' },
    { id: 73, name: 'Quảng Bình' },
    { id: 74, name: 'Quảng Trị' },
    { id: 75, name: 'Thừa Thiên – Huế' },
    { id: 76, name: 'Quảng Ngãi' },
    { id: 77, name: 'Bình Định' },
    { id: 78, name: 'Phú Yên' },
    { id: 79, name: 'Khánh Hòa' },
    { id: 81, name: 'Gia Lai' },
    { id: 82, name: 'Kon Tum' },
    { id: 83, name: 'Sóc Trăng' },
    { id: 84, name: 'Trà Vinh' },
    { id: 85, name: 'Ninh Thuận' },
    { id: 86, name: 'Bình Thuận' },
    { id: 88, name: 'Vĩnh Phúc' },
    { id: 89, name: 'Hưng Yên' },
    { id: 90, name: 'Hà Nam' },
    { id: 92, name: 'Quảng Nam' },
    { id: 93, name: 'Bình Phước' },
    { id: 94, name: 'Bạc Liêu' },
    { id: 95, name: 'Hậu Giang' },
    { id: 97, name: 'Bắc Kạn' },
    { id: 98, name: 'Bắc Giang' },
    { id: 99, name: 'Bắc Ninh' },
  ];
  
  export default provincesData;
  